[project]
name = "002-model-webapp"
version = "0.1.0"
description = "Application web de prÃ©diction avec Machine Learning"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn==1.8.0",
    "streamlit>=1.54.0",
]