[project]
name = "001-ml"
version = "0.1.0"
description = "Projet d'entrainement des modÃ¨les de machine learning"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "pathlib>=1.0.1",
    "polars>=1.38.0",
    "requests>=2.32.5",
    "scikit-learn==1.8.0",
]
