[project]
name = "003-webscraping-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "requests>=2.32.5",
    "lxml>=4.9.0",
    "pandas>=2.0.0",
]
